### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdebra** [zdebra/sep_rcc#1]
- [x] model
- [ ] service
- [ ] view (jsf and controllers)
- [ ] api communications

screens
- [ ] menu
- [ ] sign on
- [ ] client list
- [ ] client detail
- [ ] new change req
- [ ] list all submitted change requests
